name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build-binary:
    runs-on: ubuntu-latest
    env:
      TAGS: "with_quic,with_gvisor,with_utls,with_wireguard,with_clash_api"

    strategy:
      matrix:
        platform:
          - {GOOS: android, GOARCH: arm, CC: armv7a-linux-androideabi34-clang, CGO_ENABLED: 1}
          - {GOOS: android, GOARCH: arm64, CC: aarch64-linux-android34-clang, CGO_ENABLED: 0}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest go version
        id: go_version
        run: |
          echo "go_version=$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g')" >> $GITHUB_OUTPUT

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{steps.go_version.outputs.go_version}}

      - name: Setup ndk
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r27c
          add-to-path: false
          local-cache: false

      - name: Get sing-box version
        id: sing-box
        run: |
          git remote add sekai https://github.com/SagerNet/sing-box.git
          git fetch --tags sekai
          version=$(CGO_ENABLED=0 go run ./cmd/internal/read_tag)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Set tag
        run: |-
          git ls-remote --exit-code --tags origin v${{steps.sing-box.outputs.version}} || echo "PUBLISHED=false" >> "$GITHUB_ENV"
          git tag v${{steps.sing-box.outputs.version}}

      - name: Build binary
        env:
          ANDROID_NDK_HOME: ${{steps.setup-ndk.outputs.ndk-path}}
        run: |
          if [ "${{matrix.platform.GOOS}}" == "android" ]; then
            CC=${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/${{matrix.platform.CC}}
          else
            CC=""
          fi
          CGO_ENABLED=${{matrix.platform.CGO_ENABLED}} \
          GOOS=${{matrix.platform.GOOS}} \
          GOARCH=${{matrix.platform.GOARCH}} \
          CC=${CC} \
          make

      - name: Upload binary
        uses: actions/upload-artifact@v4.3.1
        with:
          name: sing-box-${{steps.sing-box.outputs.version}}-${{matrix.platform.GOOS}}-${{matrix.platform.GOARCH}}
          path: sing-box